const routes = {
    home: '/',
    dashboard: '/dashboard',
    dashboardFollowing: '/dashboard/following',
    dashboardForYou: '/dashboard/for-you',
    dashboardYourTags: '/dashboard/your-tags',
    explore: '/explore',
    exploreToday: '/explore/today',
    exploreForYou: '/explore/recommended-for-you',
    exploreTrending: '/explore/trending',
    exploreStaffPicks: '/explore/staff-picks',
    exploreAnswertime: '/explore/answertime',
    activity: '/activity',
    messages: '/messages',
    profile: '/@:nickname',
    inbox: '/inbox',
    likes: '/likes',
    following: '/following',
    blog: '/blog',
    setting: '/settings',
    settingAccount: '/settings/account',
    settingDashboard: '/settings/dashboard',
    settingNotifications: '/settings/notifications',
    settingDomains: '/settings/domains',
    settingAdFree: '/settings/ad-free-browsing',
    settingPurchases: '/settings/purchases',
    settingSubscriptions: '/settings/subscriptions',
    settingApps: '/settings/apps',
    settingPrivacy: '/settings/privacy',
    settingLabs: '/settings/labs',
    settingAccount: '/settings/account',
    settingGifts: '/settings/gifts',
    adFree: '/settings/ad-free',
    domain: '/domain',
    search: '/search',
};

export default routes;
