export const followings = {
    meta: {
        status: 200,
        msg: 'OK',
    },
    response: {
        blogs: [
            {
                name: 'cozy-vibess',
                title: '𝗖𝗢𝗭𝗬 𝗩𝗜𝗕𝗘𝗦',
                description: '<p>𝖺 𝖻𝗅𝗈𝗀 𝖿𝗈𝗋 𝖺𝗅𝗅 𝗍𝗁𝗂𝗇𝗀𝗌 𝖼𝗈𝗓𝗒. 𝗉𝗁𝗈𝗍𝗈𝗌 𝖺𝗋𝖾 𝗇𝗈𝗍 𝗆𝗂𝗇𝖾. 𝗉𝗅𝖾𝖺𝗌𝖾 𝖽𝗆 𝖿𝗈𝗋 𝗋𝖾𝗆𝗈𝗏𝖺𝗅.</p>',
                url: 'https://www.tumblr.com/blog/view/cozy-vibess',
                uuid: 't:B7PiEIp-RrqNRYBcrQNHig',
                updated: 1695078289,
                tumblrmart_accessories: {},
                can_show_badges: true,
            },
            {
                name: 'imberphile',
                title: 'Caliginous Weather',
                description: '☁\nStormcore\n|\n Raincore\n|\n Fogcore\n☁',
                url: 'https://imberphile.tumblr.com/',
                uuid: 't:YQezHFywqhMqIBbptx5yfQ',
                updated: 1695340990,
                tumblrmart_accessories: {},
                can_show_badges: true,
            },
            {
                name: 'fluffysockseason',
                title: 'Autumn is here\n🍂🌻🎃🧡',
                description: '<p>🍁Jumpers,bonfires,coffee🍁</p><p>Fluffysockseason on insta</p>',
                url: 'https://fluffysockseason.tumblr.com/',
                uuid: 't:awGdEn5Pq3MM2LwN1IV6pg',
                updated: 1690999357,
                tumblrmart_accessories: {},
                can_show_badges: true,
            },
            {
                name: 'beifongkendo',
                title: 'ZEN in TECHNICOLOR',
                description:
                    'On a journey,\nResting beneath the cherry blossoms,\nI feel myself to be in a Noh play. \n\n-<i>Matsuo Basho</i>',
                url: 'https://beifongkendo.tumblr.com/',
                uuid: 't:u4Ejj9m_qZ-bmW-Ohva6NA',
                updated: 1695365041,
                tumblrmart_accessories: {},
                can_show_badges: true,
            },
            {
                name: 'jimi-killed-the-voodoo-chil-blog',
                title: 'jimi killed the voodoo child',
                description:
                    "60's, 70's, 80's, 90's music.\n\n<br> Jimi Hendrix, Led Zeppelin, The Doors, Rory Gallagher, Frank Zappa, The Beatles, Cream, Eric Clapton,  Bob Marley, The Who, Pink Floyd, The Rolling Stones, Bob Dylan,  Patti Smith, The Clash, Queen, Pearl Jam, Red Hot Chili Peppers, Nirvana, Hole, Sonic Youth, The Stooges, Iggy Pop, Jack White, John Frusciante.. \n</br>\n\n<br>",
                url: 'https://jimi-killed-the-voodoo-chil-blog.tumblr.com/',
                uuid: 't:ycKBEwetHsLX8IRdph01yg',
                updated: 1451496557,
                tumblrmart_accessories: {},
                can_show_badges: true,
            },
            {
                name: 'pusheentheawesomecat',
                title: 'Pusheen',
                description: 'Meow!\nI am Pusheen the cat.\nThis is my blog.\n\n=＾● ⋏ ●＾=',
                url: 'https://pusheentheawesomecat.tumblr.com/',
                uuid: 't:ai8Tl0OzaYnOYQ-moK_wug',
                updated: 1424750727,
                tumblrmart_accessories: {},
                can_show_badges: true,
            },
            {
                name: 'pusheeninfo',
                title: 'Pusheen The Cat',
                description: '',
                url: 'https://pusheeninfo.tumblr.com/',
                uuid: 't:9sn0Yel6LGUQ29ig5gYWCg',
                updated: 1583697447,
                tumblrmart_accessories: {},
                can_show_badges: true,
            },
            {
                name: 'cozyautumnspices',
                title: 'All Things Autumn',
                description:
                    '<p>🎃Photos are not mine unless stated🎃 </p><p>👻Cozy Vibes👻 </p><p>🍂Autumn is back🍂</p>',
                url: 'https://cozyautumnspices.tumblr.com/',
                uuid: 't:LIHcVMyhe7Lrg4ca0eRz2w',
                updated: 1693000925,
                tumblrmart_accessories: {},
                can_show_badges: true,
            },
            {
                name: 'dailyautumn',
                title: 'autumn falls every day',
                description:
                    'sharing beautiful (and sourced!) photos of autumn since 2011<br><br>\n\nview <a href="http://dailyautumn.tumblr.com/submit">our submission guidelines</a>.<br><br>\nicon & layout photos by the mod.',
                url: 'https://dailyautumn.tumblr.com/',
                uuid: 't:VTDKFh9wvdwt4JocuETSjQ',
                updated: 1692037830,
                tumblrmart_accessories: {},
                can_show_badges: true,
            },
            {
                name: 'todayintokyo',
                title: 'Today in Tokyo',
                description: "I live in Tokyo. Everything on my blog is about Japan. Except when it's not.",
                url: 'https://todayintokyo.tumblr.com/',
                uuid: 't:YO9I7R5qEoCTiLw5D2-wzg',
                updated: 1695409311,
                tumblrmart_accessories: {},
                can_show_badges: true,
            },
            {
                name: 'tokyostreetphoto',
                title: 'Tokyo Street Photography',
                description: 'Exploring the Tokyo metropolis through the lens',
                url: 'https://tokyostreet.photo/',
                uuid: 't:pHLKMXHd_UyoSo6UgCGiAw',
                updated: 1695391006,
                tumblrmart_accessories: {},
                can_show_badges: true,
            },
            {
                name: 'rainstormpics',
                title: 'Rain Pics',
                description: '',
                url: 'https://www.tumblr.com/blog/view/rainstormpics',
                uuid: 't:9v2sA0I04_98X1DwthWzyg',
                updated: 1695409203,
                tumblrmart_accessories: {},
                can_show_badges: true,
            },
            {
                name: 'porschelove-blog',
                title: 'Porsche Love',
                description:
                    '<h3>Check out: <a href="http://fuckyeahcars.com/" target="_blank">F*ckYeahCars.com</a></h3><br />\nBrowse the Porsche family: <a href="http://porschelove.tumblr.com/tagged/356">356</a>, <a href="http://porschelove.tumblr.com/tagged/911">911</a>, <a href="http://porschelove.tumblr.com/tagged/918+Spyder">918 Spyder</a>, <a href="http://porschelove.tumblr.com/tagged/928">928</a>, <a href="http://porschelove.tumblr.com/tagged/959">959</a>, <a href="http://porschelove.tumblr.com/tagged/Carrera+GT">Carrera GT</a>, <a href="http://porschelove.tumblr.com/tagged/Boxster">Boxster</a>, <a href="http://porschelove.tumblr.com/tagged/Cayman">Cayman</a>, <a href="http://porschelove.tumblr.com/tagged/Macan">Macan</a>, <a href="http://porschelove.tumblr.com/tagged/Cayenne">Cayenne</a>, <a href="http://porschelove.tumblr.com/tagged/Panamera">Panamera</a>',
                url: 'https://porschelove-blog.tumblr.com/',
                uuid: 't:wSNhIYsdgvmxlVlTyeS1Vw',
                updated: 1419415534,
                tumblrmart_accessories: {},
                can_show_badges: true,
            },
            {
                name: 'occasional-sunshine-for-you',
                title: 'Sunshine',
                description: 'Just a Positivity Blog! You can ask me to write something specifically.',
                url: 'https://www.tumblr.com/blog/view/occasional-sunshine-for-you',
                uuid: 't:z2PKXoaZm33dufTfivx1MQ',
                updated: 1688274049,
                tumblrmart_accessories: {},
                can_show_badges: true,
            },
            {
                name: 'solutionfactory',
                title: 'Computer Programming',
                description: '<p>Everything about Computer Technology and Programming</p>',
                url: 'https://www.tumblr.com/blog/view/solutionfactory',
                uuid: 't:RxXdm7iEj2-hmzKftnKLWQ',
                updated: 1674191597,
                tumblrmart_accessories: {},
                can_show_badges: true,
            },
        ],
        total_blogs: 15,
    },
};
